included:
  - secondhand
disabled_rules:
    - trailing_whitespace
    - type_name
    - empty_enum_arguments
    - force_cast
    - force_try
opt_in_rules:
    - empty_count
    - empty_string
file_length:
  warning: 1000

line_length: 300
type_body_length: 1000
